//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LossSounds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_RolesPrivacidad
    {
        public tb_RolesPrivacidad()
        {
            this.tb_Playlist = new HashSet<tb_Playlist>();
        }
    
        public int ID_ROL { get; set; }
        public string Rol { get; set; }
    
        public virtual ICollection<tb_Playlist> tb_Playlist { get; set; }
    }
}
